# Generated by Django 2.1.3 on 2018-12-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.CharField(max_length=50, null=True, verbose_name='披薩圖片'),
        ),
    ]
