# Generated by Django 2.1.3 on 2018-12-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0002_pizza_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.AddField(
            model_name='pizza',
            name='element',
            field=models.TextField(null=True, verbose_name='披薩配料'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pic',
            field=models.ImageField(null=True, upload_to='pizza-imgae/'),
        ),
    ]
