# Generated by Django 2.1.3 on 2018-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0003_auto_20181217_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='kind_chose',
            field=models.CharField(choices=[('Beef', 'Beef'), ('Chicken', 'Chicken'), ('Mix', 'Mix'), ('Pork', 'Pork'), ('Seafood', 'Seafood'), ('Vegetable', 'Vegetable')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='element',
            field=models.TextField(null=True, verbose_name='披薩餡料'),
        ),
    ]
