# Generated by Django 2.1.3 on 2018-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0004_auto_20181218_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='isVegetarian',
            field=models.BooleanField(verbose_name='素食披薩'),
        ),
    ]
