# Generated by Django 2.1.3 on 2018-12-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0007_auto_20181218_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='isVegetarian',
        ),
    ]
