# Generated by Django 2.1.3 on 2018-12-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0008_remove_pizza_isvegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(max_length=50, verbose_name='披薩描述'),
        ),
    ]
