# Generated by Django 2.1.3 on 2018-12-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSMS', '0009_auto_20181218_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='kind_chose',
            new_name='kind',
        ),
        migrations.AddField(
            model_name='pizza',
            name='available',
            field=models.BooleanField(default=False, verbose_name='上架'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(default='0', max_length=128),
        ),
    ]
