# Generated by Django 2.1.3 on 2018-12-06 02:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='員工帳號')),
                ('title', models.CharField(max_length=8, verbose_name='員工職稱')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='會員帳號')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='使用者編號')),
                ('id_TW', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{1}[1-2]{1}[0-9]{8}$')], verbose_name='在台灣的身分證號碼')),
                ('password', models.CharField(max_length=25, verbose_name='使用者密碼')),
                ('name', models.CharField(max_length=20, verbose_name='使用者姓名')),
                ('phone_number', models.CharField(max_length=15, verbose_name='使用者電話號碼')),
                ('address', models.TextField(verbose_name='使用者住址')),
                ('age', models.PositiveIntegerField(verbose_name='使用者年齡')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='使用者性別')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0, '0<=使用者折扣<=1'), django.core.validators.MaxValueValidator(1, '0<=使用者折扣<=1')], verbose_name='使用者折扣')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MCS.User', verbose_name='會員的使用者編號'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MCS.User', verbose_name='員工的使用者編號'),
        ),
    ]
