# Generated by Django 2.1.3 on 2018-12-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='會員編號'),
        ),
    ]
