# Generated by Django 2.1.3 on 2018-12-12 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0, '0<=使用者折扣<=1'), django.core.validators.MaxValueValidator(1, '0<=使用者折扣<=1')], verbose_name='使用者折扣'),
        ),
    ]
