# Generated by Django 2.1.3 on 2018-12-12 12:23

import MCS.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCS', '0002_auto_20181212_1513'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', MCS.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(verbose_name='使用者住址'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, verbose_name='使用者年齡'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_TW',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{1}[1-2]{1}[0-9]{8}$')], verbose_name='在台灣的身分證號碼'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$')], verbose_name='使用者電話號碼'),
        ),
    ]
