# Generated by Django 2.1.3 on 2018-12-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCS', '0002_auto_20181216_1525'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
    ]
