# Generated by Django 2.1.3 on 2018-12-12 12:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MCS', '0003_auto_20181212_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='', verbose_name='使用者住址'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='使用者年齡'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9+()-]+$')], verbose_name='使用者電話號碼'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='會員的使用者編號'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='會員編號'),
        ),
    ]
