# Generated by Django 2.1.3 on 2018-12-25 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCS', '0004_auto_20181225_0056'),
        ('MCS', '0004_auto_20181224_2333'),
    ]

    operations = [
    ]
