# Generated by Django 2.1.3 on 2018-12-06 02:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MCS', '0001_initial'),
        ('PSMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(1, '最低1分'), django.core.validators.MaxValueValidator(5, '最多5分')], verbose_name='披薩評分')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCS.Member', verbose_name='會員帳號')),
                ('pizza_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSMS.Pizza', verbose_name='披薩編號')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('member_id', 'pizza_no')},
        ),
    ]
