# Generated by Django 2.1.3 on 2018-12-15 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MCS', '0001_initial'),
        ('FS', '0001_initial'),
        ('PSMS', '0002_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCS.Member', verbose_name='會員編號'),
        ),
        migrations.AddField(
            model_name='rate',
            name='pizza_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PSMS.Pizza', verbose_name='披薩編號'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('member_id', 'pizza_no')},
        ),
    ]
