# Generated by Django 2.1.3 on 2018-12-12 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCS.Member', verbose_name='會員編號'),
        ),
    ]
