# Generated by Django 2.1.3 on 2018-12-12 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FSMS', '0001_initial'),
        ('MCS', '0001_initial'),
        ('SOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkorder',
            name='empolyee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCS.Employee', verbose_name='員工編號'),
        ),
        migrations.AddField(
            model_name='checkorder',
            name='order_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SOS.Order', verbose_name='訂單編號'),
        ),
        migrations.AlterUniqueTogether(
            name='checkorder',
            unique_together={('order_no', 'empolyee_id')},
        ),
    ]
