# Generated by Django 2.1.3 on 2018-12-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FSMS', '0003_checkorder_sold_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkorder',
            name='sold_date',
        ),
    ]
