# Generated by Django 2.1.3 on 2018-12-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0003_remove_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='是否付款'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='實際出貨時間'),
        ),
    ]
