# Generated by Django 2.1.3 on 2018-12-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0004_auto_20181225_0056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisountOrder',
            new_name='DiscountOrder',
        ),
    ]
