# Generated by Django 2.1.3 on 2018-12-25 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0004_auto_20181224_2333'),
        ('SOS', '0005_auto_20181225_0119'),
    ]

    operations = [
    ]
