# Generated by Django 2.1.3 on 2018-12-25 03:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0006_merge_20181225_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='rate',
        ),
        migrations.AddField(
            model_name='discountorder',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0, '0<=折扣<=1'), django.core.validators.MaxValueValidator(1, '0<=折扣<=1')], verbose_name='折扣率'),
        ),
        migrations.AlterField(
            model_name='discountfare',
            name='sill',
            field=models.PositiveIntegerField(unique=True, verbose_name='目標金額'),
        ),
        migrations.AlterField(
            model_name='order',
            name='isFreeShipping',
            field=models.BooleanField(default=False, editable=False, verbose_name='是否免運'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='實際出貨時間'),
        ),
    ]
