# Generated by Django 2.1.3 on 2018-12-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0007_auto_20181225_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountitem',
            name='discount',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='theDiscount', to='SOS.Discount'),
        ),
    ]
