# Generated by Django 2.1.3 on 2018-12-25 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOS', '0008_auto_20181225_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discountRate',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=3, verbose_name='折扣'),
        ),
        migrations.AlterField(
            model_name='discountfare',
            name='discount_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='DiscountFare', serialize=False, to='SOS.Discount', verbose_name='折扣代碼'),
        ),
        migrations.AlterField(
            model_name='discountitem',
            name='discount',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='SOS.Discount'),
        ),
        migrations.AlterField(
            model_name='discountitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOS.Order'),
        ),
        migrations.AlterField(
            model_name='discountorder',
            name='discount_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='DiscountOrder', serialize=False, to='SOS.Discount', verbose_name='折扣代碼'),
        ),
    ]
