# Generated by Django 2.1.3 on 2018-12-02 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profits', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0, '最少0元')], verbose_name='訂單利潤')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='員工編號')),
                ('title', models.TextField(max_length=32, verbose_name='員工職稱')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=32, verbose_name='會員編號')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='訂單總價')),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='訂單產生時間')),
                ('shipped_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='實際出貨時間')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0, '0<=使用者折扣<=1'), django.core.validators.MaxValueValidator(1, '0<=使用者折扣<=1')], verbose_name='使用者折扣')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_no', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='披薩編號')),
                ('name', models.CharField(max_length=8, verbose_name='披薩名字')),
                ('description', models.TextField(verbose_name='內容簡介')),
                ('price', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0, '最低0元'), django.core.validators.MaxValueValidator(1000, '最貴1000元')], verbose_name='披薩價格')),
                ('size', models.CharField(max_length=2, verbose_name='披薩尺寸')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0, '最低0元'), django.core.validators.MaxValueValidator(500, '最貴500元')], verbose_name='披薩成本')),
                ('in_stock', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0, '最少0個'), django.core.validators.MaxValueValidator(99, '最多99個')], verbose_name='披薩庫存')),
                ('sales_volume', models.DecimalField(decimal_places=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0, '最少0個'), django.core.validators.MaxValueValidator(500, '最好是賣這麼多')], verbose_name='披薩銷售量')),
                ('click_count', models.DecimalField(decimal_places=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, '最少0次')], verbose_name='披薩點擊量')),
                ('isVegetarian', models.BooleanField(verbose_name='素食')),
                ('stars', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(0, '最低0分'), django.core.validators.MaxValueValidator(5, '最多5分')], verbose_name='披薩評分')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.DecimalField(decimal_places=0, max_digits=1, validators=[django.core.validators.MinValueValidator(0, '最低0分'), django.core.validators.MaxValueValidator(5, '最多5分')], verbose_name='披薩評分')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Member', verbose_name='會員身分證號碼')),
                ('pizza_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.Pizza', verbose_name='披薩編號')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[A-Z]{1}[1-2]{1}[0-9]{8}$')], verbose_name='身分證號碼')),
                ('password', models.CharField(max_length=20, verbose_name='使用者密碼')),
                ('name', models.CharField(max_length=20, verbose_name='使用者姓名')),
                ('phone_number', models.CharField(max_length=15, verbose_name='使用者電話號碼')),
                ('address', models.CharField(max_length=64, verbose_name='使用者住址')),
                ('age', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0, '最低0歲')], verbose_name='使用者年齡')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, verbose_name='使用者性別')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=2, validators=[django.core.validators.MinValueValidator(0, '0<=使用者折扣<=1'), django.core.validators.MaxValueValidator(1, '0<=使用者折扣<=1')], verbose_name='使用者折扣')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.ManyToManyField(to='pizza.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Member', verbose_name='會員身分證號碼'),
        ),
        migrations.AddField(
            model_name='member',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.User', verbose_name='會員身分證號碼'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.User', verbose_name='員工身分證號碼'),
        ),
        migrations.AddField(
            model_name='checkorder',
            name='empolyee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Employee', verbose_name='員工編號'),
        ),
        migrations.AddField(
            model_name='checkorder',
            name='order_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pizza.Order', verbose_name='訂單編號'),
        ),
    ]
